### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring:
  profiles: default

  #datasource:
   # driverClassName: com.mysql.jdbc.Driver
   # url: jdbc:mysql://rm-wz9857sgx78431278o.mysql.rds.aliyuncs.com:3306/ysyk?useUnicode=true&amp;characterEncoding=utf-8
   # username: gdky
   # password: gdky2016

server:
  port: 8888

endpoints:
  shutdown:
    enabled: true

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  #port: 8101
  security:
    enabled: false # management port is internal only. no need to secure it.
logging:
  path:/mylog
  file:myy.log
